version: '2'
services: 
 scarf_kereta:
  build: ./kereta_app
  ports:
   - '8090:8080'
   - '8000:8000'
  depends_on:
   - scarf_kereta_database
  environment:
   JPDA_ADDRESS: 8000
   JPDA_TRANSPORT: dt_socket
   command: /usr/local/tomcat/bin/catalina.sh jdpa start
 scarf_kereta_database:
  image: mysql:5.5
  volumes:
   - "/etc/mysql/db:/var/lib/mysql"
  ports: 
   - '3306:3306'
  restart: always
  command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: Kereta 
 scarf_winery:
   build: ./kereta_winery
   ports:
    - '8080:8080'
   depends_on:
    - scarf_kereta
