version: '2'
services: 
  scarf_kereta:
    build: ./kereta_app
    links:
      - scarf-kereta-database:scarf-kereta-database
      - scarf-nefolog:scarf-nefolog
    ports:
      - '8075:8080'
    depends_on:
      - scarf-kereta-database
      - scarf-nefolog
    networks:
      - kereta_net
  scarf-kereta-database:
    image: mysql:5.5
    container_name: scarf-kereta-database
    volumes:
      - "./kereta_db/localdb-run.sh:/localdb-run.sh"
      - "./kereta_db/data/Kereta.sql:/docker-entrypoint-initdb.d/Kereta.sql"
      - "./data-kereta-database:/var/lib/mysql:rw"
    ports: 
      - '3302:3306'
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password2
      - MYSQL_DATABASE=Kereta 
    networks:
        - kereta_net
  scarf-nefolog:
    image: sgomezsaez/scarf-nefolog:latest
    ports:
      - "8010:8080"
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=PGCloudmigration
    networks:
      - nefolog_net
networks:
  nefolog_net:
  kereta_net:
